theme: jekyll-theme-architect
title: Dynamic Wallpaper
description: Dynamic Wallpaper For macOS ["Email:<a href='mailto:macosgamedeveloper@icloud.com'>macosgamedeveloper@icloud.com</a>"]
show_downloads: true
#google_analytics:
